### ISSUE TITLE
!rpi RedW always gives me the result of !rpi RedWH

### ISSUE THREAD

**Issue by Eblancho** [gngrninja/NinjaBotCore#47]
Hello, 

First of all, thank you very much for your rather wonderful work.

I am installing your BOT on several of my discord servers and I am constantly coming across the same problem.

I'm setting up my guild, no worries.
I'm doing a !rpi RedWH, no problem.
Every time I do a !rpi RedW (a character that exists) it doesn't work anymore and give me the RedWH result.

![2019-10-02_17h33_10](https://user-images.githubusercontent.com/16915783/66058497-c35c9800-e53a-11e9-935a-8a6caecdd102.png)

So I looked in the code to see where the error can come from and I therefore step by step into GetCharMythicPlusInfo I come across this URL: 
https://raider.io/api/v1/characters/profile?region=eu&realm=confrerie-du-thorium&name=redw&fields=mythic_plus_scores%2Cmythic_plus_ranks%2Cmythic_plus_scores%2Cmythic_plus_highest_level_runs%2Cmythic_plus_recent_runs%2Cmythic_plus_best_runs%2Craid_progression

And this URL works perfectly.

So I'm wondering if your BOT is not installed behind a proxy that will do a bad management with the cache?

Thank you for your time on this issue.

Have a nice day.

**Comment by gngrninja** [comment]
I've confirmed the issue looking up that character. Even if I specify realm and region, I get an error that I'm seeing on my end.

I will do some debugging after work today, and see what I can figure out. The reason it works for you (with your guildy's name), is that it first looks for guild members, and attempts to autocomplete guild names first.

Thanks for the kind words!

**Comment by gngrninja** [comment]
@Eblancho - fixed with the latest commit. I've restarted the production bot and have done some testing.

I was able to get it to work with the following command:
!rpi redw confrerie-du-thorium eu

It will will search for the guildie first, so you may need to do the longer command option if that's the case. I did notice that the Warcraftlogs URL is bad for these lookups, which will be the next thing I look into. The rest of the data should be there, however. 

Let me know if you have any further trouble.

**Comment by Eblancho** [comment]
Indeed the long command works correctly but still not the short command (!rpi redw always returns me redwh)

But I have my workaround so it's just not that!

Thank you very much.
